- name: 4.3 Filter and tests
  hosts: r1
  gather_facts: false
  tasks:
    - name: sh ip int br
      ios_command:
        commands:
          - sh ip int brief
      register: br
    - name: Output only without unansigned
      debug:
        var: br.stdout_lines[0] | reject("search", "unassigned") | list
    - name: Output only Loopbacks
      debug:
        var: br.stdout_lines[0] | select("match", "Loopback") | list
      register: br_loopbacks
    - name: Output quantity Loopbacks
      debug:
        var: br_loopbacks | count
      
      