- name: Generate templates loopbacks
  hosts: cisco_routers 
  gather_facts: false
  tasks:
    - name: Generate output file
      template:
        src: templates/interfaces.j2
        dest: output/{{inventory_hostname}}_loopbacks.txt
        lstrip_blocks: true
      delegate_to: localhost
      run_once: true
