- name: delete ACL from interface
  ios_config:
    lines:
      - no ip access-group ACL in
    parents: interface FastEthernet0/1
- name: delete acl
  ios_config:
    lines:
      - no ip access-list extended ACL
- name: create acl
  ios_config:
    lines:
      - permit tcp 10.10.11.0 0.0.0.255 any eq 80
      - permit tcp 10.10.11.0 0.0.0.255 any eq 22
      - permit icmp any any
    parents: ip access-list extended ACL
- name: add acl to interface
  ios_config:
    lines:
      ip access-group ACL in
    parents: interface FastEthernet0/1